language: go

go:
  - "1.14"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install zip unzip wget
  - wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
  - sudo unzip ninja-linux.zip -d /usr/local/bin/
  - sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
services:
  - docker
script:
  - go get -u github.com YaroslavChirko/design-practice-2-template
  - chmod +x ./bood
  - chmod +x entry.sh
  - docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --build --exit-code-from test
  
