FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

# TODO: Змініть на власну реалізацію системи збірки
RUN go get -u github.com/YaroslavChirko/design-practice-2-template/build/cmd/bood

WORKDIR /go/src/practice-3
COPY . .

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
RUN cp ./instructions/test/build.bood ./
ENTRYPOINT ["bood"]
#ENTRYPOINT ["bood", "integration-tests"]
#ENTRYPOINT ["echo", "ok"]
