FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/YaroslavChirko/design-practice-2-template/build/cmd/bood

WORKDIR /go/src/practice-3
COPY . .

RUN go get -u gopkg.in/check.v1
RUN cp ./instructions/test/build.bood ./
ENTRYPOINT ["bood"]
